name: automatic_animated_list
description: AnimatedList which computes the item deltas each time the underlying list gets updated, and animates the list tiles automatically.
version: 1.1.0
homepage: https://github.com/gkpln3

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  diffutil_dart: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
